### ISSUE TITLE
🖐 Add a counter for how many people subscribed and how many beds were proposed

### ISSUE THREAD

**Issue by fabrahaingo** [Find-Shelter/find-shelter#11]
This is entirely based on what the German website (https://elinor.network/gastfreundschaft-ukraine/) does. This is a good idea to make people realise that others are engaged, too.

Incredible fact: on the 24/02/2022, there were 5.000 beds promises. Today (27/02/2022), they're at 48.000 😍

**Comment by petrussola** [comment]
I can give this one a go this evening!

**Comment by CamilleHbp** [comment]
Merged #19 - Issue is resolved :)
