### ISSUE TITLE
📍 Add a route that returns the first 5 result of a Mapbox search

### ISSUE THREAD

**Issue by fabrahaingo** [Find-Shelter/find-shelter#4]
I've been playing a little with the API of Mapbox (https://docs.mapbox.com/playground/geocoding/)

This seems to be a nice too for autocompletion in the `address` field.
Creating a specific route in the API is necessary because otherwise, we would expose our Mapbox Token on the frontend...

PS: this would then work exactly like Algolia Places (https://community.algolia.com/places/). Then problem with Algolia Places is that support for this service is getting dropped soon.

**Comment by elliotwutingfeng** [comment]
Hi, I am a React developer (though this project is in Vue) and I have worked with Mapbox before.

**Comment by elliotwutingfeng** [comment]
Sure, I'll take up this one.
